import Head from "next/head";
import Homepage from "../src/components/home/Homepage";

export default function Home({ title, city }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homepage city={city} />
    </>
  );
}

export async function getServerSideProps() {
  const data = await import("../data/data.json");

  console.log("I am coming from getServerSideProps function");
  return {
    props: {
      title: "I am coming from server side",
      city: data.events_categories,
    },
  };
}
